spring:
  application:
    name: booking-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/book-db
# Allocate port dynamically
server:
  port: 0
# Generate a unique name for the instance
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}