spring:
  application:
    name: product-service
server:
  port: 0
# Generate a unique name for the instance
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

app:
  prop1: This is prop 2 updated